### ISSUE TITLE
auro-input; upgrade and feature support (combo-issue) 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-input#40]
# User story

The scope of this story is to encompass the following open issues to be delivered. The following list is prioritized. 

### Updates and issues to address

- [x] remove light DOM support https://github.com/AlaskaAirlines/auro-input/issues/39
- [x] address increased bundle size https://github.com/AlaskaAirlines/auro-input/issues/36
- [x] default values for boolean attributes https://github.com/AlaskaAirlines/auro-input/issues/35
- [x] address label issues https://github.com/AlaskaAirlines/auro-input/issues/34
- [x] CC and Firefox issue https://github.com/AlaskaAirlines/auro-input/issues/26
- [x] upgrade https://github.com/AlaskaAirlines/auro-input/issues/15

### Prior to next major release 

It is **important that we communicate prior to the next major release** that we will be changing the npm namespace. See https://github.com/AlaskaAirlines/auro-radio/commit/2e894a0af517b633a4b24cbc2b3156cd96487d1d for the update to be used. 

## Development process

This is a placeholder issue for all the issues to be in a single release. As each issue is put into play, please update the issue as IN PROGRESS and move it into the WIP column. Please leave this issue in TO DO until all linked issues are completed. 

## Definition of “Done” (exit criteria)

This issue will be considered complete and all features released once all issues listed are considered complete.

**Comment by jason-capsule42** [comment]
Removing ticket #23 from this ticket.
